[versions]
activityKtx = "1.13.0"
agp = "9.4.1"
appcompat = "1.8.0"
compileSdk = "37"
coreKtx = "1.19.1"
espressoCore = "3.7.0"
fragmentKtx = "1.9.1"
junit = "4.13.2"
junitVersion = "1.3.0"
leakcanaryAndroid = "2.14"
loggingInterceptor = "5.5.0"
material = "1.14.0"
materialVersion = "1.12.1"
minSdk = "26"
constraintlayout = "2.2.2"
detektVersion = "1.23.8"
kotlin = "2.4.20"
jdk = "21"
browserVersion = "1.10.0"
fileSystemVersion = "0.0.1-alpha2"
glideVersion = "5.0.9"
lifecycleService = "2.11.0"
logbackAndroidVersion = "3.0.0"
multidex = "2.0.1"
navigationFragmentKtx = "2.10.2"
navVersion = "2.10.2"
retrofit = "3.0.0"
retrofitMock = "3.0.0"
roomCompiler = "2.8.5"
roomTestingVersion = "2.8.5"
swipeRefreshLayout = "1.2.0"
simplemagicVersion = "1.17"
uiTooling = "1.12.1"
windowVersion = "1.5.1"
webkitVersion = "1.17.1"
preferenceKtxVersion = "1.2.1"
kspVersion = "2.3.6"
commonUiList = "0.0.1-alpha1"
workMultiprocess = "2.12.0"
workTesting = "2.12.0"
easylauncher = "6.4.1"
lifecycleRuntimeKtx = "2.11.0"
vanniktechPublish = "0.37.0"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "loggingInterceptor" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomCompiler" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workTesting" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workMultiprocess" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workMultiprocess" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
browser = { module = "androidx.browser:browser", version.ref = "browserVersion" }
common-vm-ktx = { module = "io.github.storytellerf:common-vm-ktx", version.ref = "commonUiList" }
common-ui = { module = "io.github.storytellerf:common-ui", version.ref = "commonUiList" }
compat-ktx = { module = "io.github.storytellerf:compat-ktx", version.ref = "commonUiList" }
ext-func-compiler = { module = "io.github.storytellerf:ext-func-compiler", version.ref = "commonUiList" }
ext-func-definition = { module = "io.github.storytellerf:ext-func-definition", version.ref = "commonUiList" }
ui-list = { module = "io.github.storytellerf:ui-list", version.ref = "commonUiList" }
view-holder-compose = { module = "io.github.storytellerf:view-holder-compose", version.ref = "commonUiList" }
ui-list-annotation-compiler-ksp = { module = "io.github.storytellerf:ui-list-annotation-compiler-ksp", version.ref = "commonUiList" }
ui-list-annotation-definition = { module = "io.github.storytellerf:ui-list-annotation-definition", version.ref = "commonUiList" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektVersion" }
detekt-rules-libraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detektVersion" }
detekt-rules-ruleauthors = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ruleauthors", version.ref = "detektVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
file-system-archive = { module = "io.github.storytellerf:file-system-archive", version.ref = "fileSystemVersion" }
file-system = { module = "io.github.storytellerf:file-system", version.ref = "fileSystemVersion" }
file-system-ktx = { module = "io.github.storytellerf:file-system-ktx", version.ref = "fileSystemVersion" }
file-system-local = { module = "io.github.storytellerf:file-system-local", version.ref = "fileSystemVersion" }
file-system-memory = { module = "io.github.storytellerf:file-system-memory", version.ref = "fileSystemVersion" }
file-system-remote = { module = "io.github.storytellerf:file-system-remote", version.ref = "fileSystemVersion" }
#file-system-root = { module = "io.github.storytellerf:file-system-root", version.ref = "fileSystemVersion" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleService" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navVersion" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtxVersion" }
retrofit-mock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofitMock" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
simplemagic = { module = "com.j256.simplemagic:simplemagic", version.ref = "simplemagicVersion" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkitVersion" }
window = { module = "androidx.window:window", version.ref = "windowVersion" }
room-testing = { module = "androidx.room:room-testing", version.ref = "roomTestingVersion" }
swipe-refresh-layout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefreshLayout" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroidVersion" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "roomCompiler" }
easylauncher = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVersion" }
safeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navVersion" }
vanniktechPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechPublish" }
